name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy Team Manual
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1

      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 #v4.0.0
        with:
          node-version: "14"

      - uses: ruby/setup-ruby@8575951200e472d5f2d95c625da0c7bec8217c42 #v1.161.0
        with:
          bundler-cache: true

      - name: Build middleman site
        id: build
        run: bundle exec middleman build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@a753861a5debcf57bf8b404356158c8e1e33150c
        with:
          path: 'build'

      - name: Deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@13b55b33dd8996121833dbc1db458c793a334630

      - name: Slack notify on failure
        if: failure()
        uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117
        with:
          payload: |
            {
              "text": "Deployment of Paas Team Manual with commit ${{ github.sha }} FAILED."
            }
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK