name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

concurrency: production

jobs:
  deploy:
    name: Deploy Team Manual
    environment: production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 #v3.5.3

      - uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 #v3.7.0
        with:
          node-version: "14"

      - uses: ruby/setup-ruby@250fcd6a742febb1123a77a841497ccaa8b9e939 #v1.152.0
        with:
          bundler-cache: true

      - run: sudo apt install git

      - name: Build
        id: build
        run: bundle exec middleman build

      - name: Deploy 🚀
        id: deploy
        uses: JamesIves/github-pages-deploy-action@a1ea191d508feb8485aceba848389d49f80ca2dc #v4.4.3
        with:
          folder: build
          branch: gh-pages

      - name: Slack notify on failure
        if: failure()
        uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117
        with:
          payload: |
            {
              "text": "Deployment of ${{ github.event.pull_request.html_url }} FAILED"
            }
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
