name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

concurrency: production

jobs:
  deploy:
    name: Deploy Team Manual
    environment: production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b #v3.0.2

      - uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 #v3.7.0
        with:
          node-version: "14"

      - uses: ruby/setup-ruby@250fcd6a742febb1123a77a841497ccaa8b9e939 #v1.152.0
        with:
          bundler-cache: true

      - run: sudo apt install git

      - name: Build
        id: build
        run: bundle exec middleman build

      - name: Deploy 🚀
        id: deploy
        uses: JamesIves/github-pages-deploy-action@e6d003d0839927f5a4b998bfd92ed8e448fde37a #v4.3.4
        with:
          folder: build
          branch: gh-pages

      - name: Slack notify on failure
        if: failure()
        uses: slackapi/slack-github-action@936158bbe252e9a6062e793ea4609642c966e302
        with:
          payload: |
            {
              "text": "Deployment of ${{ github.event.pull_request.html_url }} FAILED"
            }
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
