---
name: pr-tests
on: pull_request

env:
  NODE_VERSION: "14.x"
  PYTHON_VERSION: "3.x"
  NODE_ENV: development

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 #v4.1.2

      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a #v4.2.0
        with:
          node-version: "${{env.NODE_VERSION}}"

      - uses: ruby/setup-ruby@5f19ec79cedfadb78ab837f95b87734d0003c899 #v1.173.0
        with:
          bundler-cache: true

      - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c #v5.0.0
        with:
          python-version: "${{env.PYTHON_VERSION}}"

      - run: pip install --user -r requirements.txt

      - run: sudo apt install git

      - name: Build
        run: bundle exec middleman build
