---
name: pr-tests
on: pull_request

env:
  NODE_VERSION: "14.x"
  PYTHON_VERSION: "3.x"
  NODE_ENV: development

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #v4.0.0

      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d #v3.8.1
        with:
          node-version: "${{env.NODE_VERSION}}"

      - uses: ruby/setup-ruby@5311f05890856149502132d25c4a24985a00d426 #v1.153.0
        with:
          bundler-cache: true

      - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 #v4.7.0
        with:
          python-version: "${{env.PYTHON_VERSION}}"

      - run: pip install --user -r requirements.txt

      - run: sudo apt install git

      - name: Build
        run: bundle exec middleman build
