---
name: pr-tests
on: pull_request

env:
  NODE_VERSION: "14.x"
  PYTHON_VERSION: "3.x"
  NODE_ENV: development

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1

      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 #v4.0.0
        with:
          node-version: "${{env.NODE_VERSION}}"

      - uses: ruby/setup-ruby@036ef458ddccddb148a2b9fb67e95a22fdbf728b #v1.160.0
        with:
          bundler-cache: true

      - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 #v4.7.1
        with:
          python-version: "${{env.PYTHON_VERSION}}"

      - run: pip install --user -r requirements.txt

      - run: sudo apt install git

      - name: Build
        run: bundle exec middleman build
