---
name: pr-tests
on: pull_request

env:
  NODE_VERSION: "14.x"
  PYTHON_VERSION: "3.x"
  NODE_ENV: development

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 #v3.5.3

      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d #v3.8.1
        with:
          node-version: "${{env.NODE_VERSION}}"

      - uses: ruby/setup-ruby@250fcd6a742febb1123a77a841497ccaa8b9e939 #v1.152.0
        with:
          bundler-cache: true

      - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 #v4.7.0
        with:
          python-version: "${{env.PYTHON_VERSION}}"

      - run: pip install --user -r requirements.txt

      - run: sudo apt install git

      - name: Build
        run: bundle exec middleman build
