---
name: pr-tests
on: pull_request

env:
  NODE_VERSION: "14.x"
  PYTHON_VERSION: "3.x"
  NODE_ENV: development

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b #v3.0.2

      - uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 #v3.7.0
        with:
          node-version: "${{env.NODE_VERSION}}"

      - uses: ruby/setup-ruby@250fcd6a742febb1123a77a841497ccaa8b9e939 #v1.152.0
        with:
          bundler-cache: true

      - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 #v4.7.0
        with:
          python-version: "${{env.PYTHON_VERSION}}"

      - run: pip install --user -r requirements.txt

      - run: sudo apt install git

      - name: Build
        run: bundle exec middleman build
